import{test}from"node:test";import assert from"node:assert/strict";import{addAndSave,deleteIfConfirmed,summaryModel}from"../main.js";import{ROOMS}from"../logic.js";
function ok(){return{ok:true,error:null}}
function fail(){return{ok:false,error:"Could not save boxes. Your changes may not persist."}}
test("addAndSave validation",()=>{const b=[{id:"1",label:"A",room:"Kitchen",boxNumber:1}];const r=addAndSave(b,"","Kitchen",ok);assert.equal(r.kind,"validation");assert.equal(r.state,b);assert.match(r.error,/Enter a label/);assert.equal(r.box,null)})
test("addAndSave success",()=>{const r=addAndSave([],"Dishes","Kitchen",ok);assert.equal(r.kind,"ok");assert.equal(r.state.length,1);assert.equal(r.box.boxNumber,1);assert.equal(r.error,null)})
test("addAndSave save failure rolls back",()=>{const b=[{id:"1",label:"A",room:"Kitchen",boxNumber:1}];const r=addAndSave(b,"New","Bedroom",fail);assert.equal(r.kind,"storage");assert.equal(r.state,b);assert.match(r.error,/Could not save/)})
test("deleteIfConfirmed noop without pending",()=>{assert.equal(deleteIfConfirmed([],null,"accept").kind,"idle");assert.equal(deleteIfConfirmed([],"1","keep").kind,"idle")})
test("deleteIfConfirmed only deletes on accept",()=>{const b=[{id:"1",label:"A",room:"Kitchen",boxNumber:1},{id:"2",label:"B",room:"Bedroom",boxNumber:2}];const r=deleteIfConfirmed(b,"1","accept",ok);assert.equal(r.kind,"ok");assert.equal(r.state.length,1);assert.equal(r.state[0].id,"2")})
test("deleteIfConfirmed save failure rolls back",()=>{const b=[{id:"1",label:"A",room:"Kitchen",boxNumber:1}];const r=deleteIfConfirmed(b,"1","accept",fail);assert.equal(r.kind,"storage");assert.equal(r.state,b);assert.match(r.error,/Could not save/)})
test("summaryModel empty",()=>{const m=summaryModel([]);assert.equal(m.total,0);assert.equal(m.empty,true);assert.deepEqual(m.rows,[])})
test("summaryModel rows",()=>{const b=[{id:"1",label:"A",room:"Kitchen",boxNumber:1},{id:"2",label:"B",room:"Kitchen",boxNumber:2},{id:"3",label:"C",room:"Bathroom",boxNumber:3}];const m=summaryModel(b);assert.equal(m.empty,false);assert.equal(m.total,3);assert.deepEqual(m.rows,[{room:"Kitchen",count:2},{room:"Bathroom",count:1}]);assert.ok(ROOMS.indexOf("Kitchen")<ROOMS.indexOf("Bathroom"))})