import{test}from"node:test";import assert from"node:assert/strict";import{readBoxes,saveBoxes,STORAGE_KEY}from"../storage.js";
function mem(i={}){const s=new Map(Object.entries(i));return{getItem(k){return s.has(k)?s.get(k):null},setItem(k,v){s.set(k,String(v))},_store:s}}
test("readBoxes empty",()=>{const r=readBoxes(mem());assert.equal(r.error,null);assert.deepEqual(r.state,[])})
test("readBoxes getItem throws",()=>{const r=readBoxes({getItem(){throw Error("x")}});assert.equal(r.state.length,0);assert.match(r.error,/Could not load/)})
test("readBoxes malformed JSON",()=>{const r=readBoxes(mem({[STORAGE_KEY]:"{bad"}));assert.equal(r.state.length,0);assert.match(r.error,/corrupted/)})
test("readBoxes drops bad rows",()=>{const r=readBoxes(mem({[STORAGE_KEY]:JSON.stringify([{id:"1",label:"Good",room:"Kitchen",boxNumber:1},"junk",{id:"2",label:"",room:"Kitchen",boxNumber:2},{id:"3",label:"Also Good",room:"Bedroom",boxNumber:3}])}));assert.equal(r.error,null);assert.equal(r.state.length,2);assert.equal(r.state[0].label,"Good");assert.equal(r.state[1].label,"Also Good")})
test("readBoxes dedupes ids, repairs bad boxNumber",()=>{const r=readBoxes(mem({[STORAGE_KEY]:JSON.stringify([{id:"dup",label:"First",room:"Kitchen",boxNumber:"bad"},{id:"dup",label:"Second",room:"Kitchen",boxNumber:2}])}));assert.equal(r.state.length,1);assert.equal(r.state[0].boxNumber,1)})
test("prototype pollution ignored",()=>{readBoxes(mem({[STORAGE_KEY]:'[{"id":"1","label":"Safe","room":"Kitchen","boxNumber":1,"__proto__":{"polluted":true}}]'}));assert.equal(({}).polluted,void 0)})
test("saveBoxes setItem throws",()=>{const r=saveBoxes([{id:"1",label:"A",room:"Kitchen",boxNumber:1}],{setItem(){throw Error("x")}});assert.equal(r.ok,false);assert.match(r.error,/Could not save/)})
test("saveBoxes strips extra fields",()=>{const m=mem();saveBoxes([{id:"1",label:"Plates",room:"Kitchen",boxNumber:1,extra:"x"}],m);const d=JSON.parse(m._store.get(STORAGE_KEY));assert.equal(d[0].extra,void 0);assert.equal(d[0].label,"Plates")})